# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    twilio.client:
       class: Twilio\Rest\Client
       arguments: ['%env(TW_ID)%', '%env(TW_TOKEN)%']
  
    # Add an alias for the twilio.client service
    Twilio\Rest\Client: '@twilio.client'

    app.validator.e164_number:
        class: AppBundle\Validator\Constraints\E164NumberValidator
        arguments: ['@twilio.client']
        tags:
            - { name: validator.constraint_validator }
    
    freshdesk.client:
       class: Freshdesk\Api
       arguments: ['%env(FRESHDESK_API_KEY)%', 'https://beddertravel.freshdesk.com']
  
    # Add an alias for the freshdesk.client service
    Freshdesk\Api: '@freshdesk.client'

    app.jwt_token_authenticator:
        class: App\Security\JwtAuthenticator
        parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
        autowire: false
        autoconfigure: false
    
    Flosch\Bundle\StripeBundle\Stripe\StripeClient: '@flosch.stripe.client'

    Swap\Swap: '@florianv_swap.swap'
