jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    property_naming:
        ## Do not remove this line. It is not well documented, but it keeps to CamalCase on JsonSerilalize. We don't sant snake_case.
        id: 'jms_serializer.identical_property_naming_strategy'