backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
  branch: master # Branch to update (master by default)

media_folder: "frontend/public/images" # Folder where user uploaded files should go
public_folder: "/images" # The src attribute for uploaded media will begin with

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - name: "home"
        label: "Home"
        file: "frontend/src/containers/HomePage/text.json"
        description: "Texte pour la page Home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
      - name: "faq"
        label: "FAQ"
        file: "frontend/src/containers/FaqPage/data.json"
        description: "Texte pour la page FAQ"
        fields:
          - name: questions
            label: "Questions"
            widget: list
            allow_add: true
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "RÃ©ponse", name: "answer", widget: "text"}
      - name: "about"
        label: "About"
        file: "frontend/src/containers/AboutPage/data.json"
        description: "Texte pour la page About"
        fields:
          - {label: "Texte", name: "text", widget: "markdown"}
      - name: "privacy-policy"
        label: "Privacy Policy"
        file: "frontend/src/containers/PrivacyPolicyPage/data.json"
        description: "Text for your privacy policy"
        fields:
          - {label: "Texte", name: "text", widget: "markdown"}
      - name: "terms-and-conditions"
        label: "Terms and conditions"
        file: "frontend/src/containers/TermsPage/data.json"
        description: "Text for your terms and conditions"
        fields:
          - {label: "Texte", name: "text", widget: "markdown"}